-- A group is a row; every gradebook column points at one through group_id
create table "public"."gradebook_column_groups" (
    "id" bigint generated by default as identity not null,
    "class_id" bigint not null,
    "title" text not null,
    "sort_order" integer not null default 0
);

create unique index gradebook_column_groups_pkey on public.gradebook_column_groups using btree (id);
create unique index gradebook_column_groups_class_id_id_key on public.gradebook_column_groups using btree (class_id, id);
create index gradebook_column_groups_class_id_idx on public.gradebook_column_groups using btree (class_id);

alter table "public"."gradebook_column_groups" add constraint "gradebook_column_groups_pkey" PRIMARY KEY using index "gradebook_column_groups_pkey";
alter table "public"."gradebook_column_groups" add constraint "gradebook_column_groups_class_id_fkey" FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE CASCADE;
alter table "public"."gradebook_column_groups" add constraint "gradebook_column_groups_title_check" CHECK ((btrim(title) <> ''::text));
alter table "public"."gradebook_column_groups" add constraint "gradebook_column_groups_class_id_id_key" UNIQUE using index "gradebook_column_groups_class_id_id_key";

alter table "public"."gradebook_column_groups" enable row level security;

alter table "public"."gradebook_columns" add column "group_id" bigint;
create index gradebook_columns_group_id_idx on public.gradebook_columns using btree (group_id);

create policy "instructors CRUD"
on "public"."gradebook_column_groups"
as permissive
for all
to public
using (authorizeforclassinstructor(class_id))
with check (authorizeforclassinstructor(class_id));

-- Students only see groups holding a column they can see, matching gradebook_columns
create policy "everyone in class can view"
on "public"."gradebook_column_groups"
as permissive
for select
to public
using (
  authorizeforclassgrader(class_id) OR 
  (
    authorizeforclass(class_id) AND 
    (EXISTS (
      SELECT 1
      FROM public.gradebook_columns
      WHERE (gradebook_columns.group_id = gradebook_column_groups.id) AND ((COALESCE(gradebook_columns.instructor_only, false) = false) OR (gradebook_columns.released = true))
    ))
  )
);

-- Group title for a column slug, e.g. assignment-lab-1 -> Lab, ai-usage-log-2 -> Ai Usage Log
create function "public"."gradebook_column_group_title"(p_slug text) returns text
    language plpgsql immutable
    as $$
DECLARE
    t text;
BEGIN
    t := regexp_replace(p_slug, '^assignment-(?=[^-]+-)', '');
    t := regexp_replace(t, '-[0-9]+$', '');
    t := initcap(translate(t, '-_', '  '));
    RETURN COALESCE(NULLIF(btrim(t), ''), 'Other');
END;
$$;

-- Backfill: one group per title per class, ordered by each group's first column
insert into public.gradebook_column_groups (class_id, title, sort_order)
select
  class_id,
  public.gradebook_column_group_title(slug) as title,
  CAST(row_number() over (partition by class_id order by min(sort_order)) AS integer) - 1 as sort_order
from public.gradebook_columns
group by class_id, public.gradebook_column_group_title(slug);

update public.gradebook_columns
set group_id = g.id
from public.gradebook_column_groups g
where gradebook_columns.class_id = g.class_id
  and public.gradebook_column_group_title(gradebook_columns.slug) = g.title;

-- Every column is in exactly one group of its own class
alter table "public"."gradebook_columns" add constraint "gradebook_columns_group_id_check" CHECK (group_id IS NOT NULL);
alter table "public"."gradebook_columns" add constraint "gradebook_columns_class_id_group_id_fkey" FOREIGN KEY (class_id, group_id) REFERENCES public.gradebook_column_groups(class_id, id);

-- New columns join the group of the latest column with the same title, or start a new group at the end
create function "public"."gradebook_columns_set_group"() returns trigger
    language plpgsql security definer set search_path = 'public'
    as $$
DECLARE
    v_title text;
    v_group_id bigint;
    v_sort_order integer;
BEGIN
    IF NEW.group_id IS NOT NULL THEN
        RETURN NEW;
    END IF;

    PERFORM pg_advisory_xact_lock(NEW.gradebook_id);

    v_title := gradebook_column_group_title(NEW.slug);

    SELECT group_id INTO v_group_id
    FROM gradebook_columns
    WHERE class_id = NEW.class_id
      AND gradebook_column_group_title(slug) = v_title
    ORDER BY sort_order DESC NULLS LAST
    LIMIT 1;

    IF v_group_id IS NOT NULL THEN
        NEW.group_id := v_group_id;
    ELSE
        SELECT COALESCE(MAX(sort_order) + 1, 0) INTO v_sort_order
        FROM gradebook_column_groups
        WHERE class_id = NEW.class_id;

        INSERT INTO gradebook_column_groups (class_id, title, sort_order)
        VALUES (NEW.class_id, v_title, v_sort_order)
        RETURNING id INTO NEW.group_id;
    END IF;

    RETURN NEW;
END;
$$;

create trigger "gradebook_columns_set_group_trigger"
    before insert on "public"."gradebook_columns"
    for each row
    execute function "public"."gradebook_columns_set_group"();

-- Reorder only touches groups, never columns, so membership can't change
create function "public"."reorder_gradebook_column_groups"(p_class_id bigint, p_group_ids bigint[]) returns void
    language plpgsql security invoker
    as $$
BEGIN
    IF (SELECT array_agg(id ORDER BY id) FROM public.gradebook_column_groups WHERE class_id = p_class_id)
       IS DISTINCT FROM (SELECT array_agg(x ORDER BY x) FROM unnest(p_group_ids) x) THEN
        RAISE EXCEPTION 'p_group_ids must list every group in the class exactly once';
    END IF;

    UPDATE public.gradebook_column_groups
    SET sort_order = CAST(u.ordinality AS integer) - 1
    FROM unnest(p_group_ids) WITH ORDINALITY AS u(id, ordinality)
    WHERE public.gradebook_column_groups.id = u.id
      AND public.gradebook_column_groups.class_id = p_class_id;
END;
$$;
